blank_issues_enabled: false
contact_links:
  - name: Suggestion / Feature Request
    url: https://discord.com/channels/561258884719968257/1105201160324919376/1105201498830422046
    about: Use our Discord feedback section to provide a suggestion/feature request.
